### ISSUE TITLE
Login fails in 404 Fot Found

### ISSUE THREAD

**Issue by Caesar2011** [bitnami/bitnami-docker-harbor-portal#15]
**Description**

When I login to my harbor registry using `docker login something.int` I am getting asked for a username and password. After that it tries to log me in. I also get a token, but using the token on the endpoint `GET /v2/` results in a 404 Not Found.

**Steps to reproduce the issue:**

1. Use latest compose: 2-debian-10
2. Apply `registryctl`-fix of https://github.com/bitnami/bitnami-docker-harbor-registryctl/issues/1
3. Change core env to `EXT_ENDPOINT=https://something.int:443`

**Describe the results you received:**

(Logs at the bottom)

The actual login process itself seems to work. I was able to reproduce it with firefox. I get a token to use on `GET /v2/`. Without that token it returns a 401 (as an JSON procuces by core). With that token I get an 404 Not Found (which looked like an nginx page with HTML) - strange. The terminal states `Error response from daemon: login attempt to https://something.int/v2/ failed with status: 404 Not Found`.

Using a diffrent user than `admin`/`bitnami` who does not exist results in `Error response from daemon: Get https://something.int/v2/: unauthorized: authentication required`.

Changing the nginx config from `core:5000` to `registry:5000` as described https://github.com/bitnami/bitnami-docker-harbor-portal/issues/4 works like a charm but only with `harbor_registy_user` and `harbor_registry_password` respectively. And that solution bypass all user auth mechanism.

**Describe the results you expected:**

A successful login :D

**Additional information you deem important (e.g. issue happens only occasionally):**

Job Service is searching for a config and sends requests to `https://www.core.com` instead of the configured `http://core:8080`. Another bug which a already half-fixed by using manually setting ip addresses. It has no influence to this problem as the login error occurs in any case. xD

**Version**

- Output of `docker version`:

Client:

```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Server:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

Client:

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 2
  Paused: 0
  Stopped: 4
 Images: 236
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.789GiB
 Name: docker-desktop
 ID: 6PI5:NOJ3:PCI6:3IBV:H5A2:2JCY:J2OO:O4KZ:BJLH:T6B3:KNY3:VV5V
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 56
  Goroutines: 60
  System Time: 2020-10-13T07:45:55.8218508Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

I added an nginx network to be able to reach it from my main reverse proxy. Because nginx logs every request in the compose logs every request gets through.

I also changed the binds to folder binds.

I changed all secrets to passwords in a form of `hxmxE34sBtFVhKbQ9mgLtsx7`

```
version: '2'

services:
  registry:
    image: docker.io/bitnami/harbor-registry:2-debian-10
    environment:
      - REGISTRY_HTTP_SECRET=reg_recret
    volumes:
      - ./registry-data:/storage
      - ./config/registry/:/etc/registry/:ro
  registryctl:
    image: docker.io/bitnami/harbor-registryctl:2-debian-10
    environment:
      - CORE_SECRET=core_secret
      - JOBSERVICE_SECRET=jobservice_secret
      - REGISTRY_HTTP_SECRET=reg_secret
    volumes:
      - ./registry-data:/storage
      - ./config/registry/:/etc/registry/:ro
      - ./config/registryctl/config.yml:/etc/registryctl/config.yml:ro
  postgresql:
    image: docker.io/bitnami/postgresql:11-debian-10
    container_name: harbor-db
    environment:
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=registry
    volumes:
      - ./postgresql-data:/bitnami/postgresql
  core:
    image: docker.io/bitnami/harbor-core:2-debian-10
    container_name: harbor-core
    depends_on:
      - registry
      - chartmuseum
    environment:
      - CORE_KEY=core_key
      - _REDIS_URL=redis:6379,100,
      - SYNC_REGISTRY=false
      - CHART_CACHE_DRIVER=redis
      - _REDIS_URL_REG=redis://redis:6379/1
      - PORT=8080
      - LOG_LEVEL=debug
      - EXT_ENDPOINT=https://something.int:443
      - DATABASE_TYPE=postgresql
      - REGISTRY_CONTROLLER_URL=http://registryctl:8080
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=registry
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_SSLMODE=disable
      - REGISTRY_URL=http://registry:5000
      - TOKEN_SERVICE_URL=http://core:8080/service/token
      - HARBOR_ADMIN_PASSWORD=bitnami
      - CORE_SECRET=core_secret
      - JOBSERVICE_SECRET=jobservice_secret
      - ADMIRAL_URL=
      - WITH_NOTARY=False
      - WITH_CLAIR=False
      - WITH_CHARTMUSEUM=True
      - CHART_REPOSITORY_URL=http://chartmuseum:8080
      - CORE_URL=http://core:8080
      - JOBSERVICE_URL=http://jobservice:8080
      - REGISTRY_STORAGE_PROVIDER_NAME=filesystem
      - REGISTRY_CREDENTIAL_USERNAME=harbor_registry_user
      - REGISTRY_CREDENTIAL_PASSWORD=harbor_registry_password
      - READ_ONLY=false
      - RELOAD_KEY=
    volumes:
      - ./core-data:/data
      - ./config/core/app.conf:/etc/core/app.conf:ro
      - ./config/core/private_key.pem:/etc/core/private_key.pem:ro
    networks:
      - default
      - nginx
  portal:
    image: docker.io/bitnami/harbor-portal:2-debian-10
    container_name: harbor-portal
    depends_on:
      - core
  jobservice:
    image: docker.io/bitnami/harbor-jobservice:2-debian-10
    container_name: harbor-jobservice
    depends_on:
      - redis
      - core
    environment:
      - CORE_SECRET=core_secret
      - JOBSERVICE_SECRET=jobservice-secret
      - CORE_URL=http://core:8080
      - REGISTRY_CONTROLLER_URL=http://registryctl:8080
      - REGISTRY_CREDENTIAL_USERNAME=harbor_registry_user
      - REGISTRY_CREDENTIAL_PASSWORD=harbor_registry_password
    volumes:
      - ./jobservice-data:/var/log/jobs
      - ./config/jobservice/config.yml:/etc/jobservice/config.yml:ro
  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  harbor-nginx:
    image: docker.io/bitnami/nginx:1.19-debian-10
    container_name: nginx
    volumes:
      - ./config/proxy/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
      - ./config/registry/root.crt:/opt/bitnami/nginx/root.crt:ro
    networks:
      - default
      - nginx
    depends_on:
      - postgresql
      - registry
      - core
      - portal
  chartmuseum:
    container_name: chartmuseum
    image: docker.io/bitnami/chartmuseum:0-debian-10
    environment:
      - CACHE=redis
      - CACHE_REDIS_ADDR=redis:6379
      - CACHE_REDIS_DB=1
      - DEPTH=1
      - PORT=8080
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/bitnami/data
      - ALLOW_OVERWRITE=true
      - INDEX_LIMIT=0
    volumes:
      - ./chartmuseum-data:/bitnami/data
      
networks:
  nginx:
    external: true
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Logs on `docker login`:

```
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 006a0dc1-6398-4fa2-9f37-2ac3f0023cd0 to the logger for the request GET /v2/
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:52]: In artifact info middleware, url: /v2/
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/server/middleware/security/unauthorized.go:29][requestID="006a0dc1-6398-4fa2-9f37-2ac3f0023cd0"]: an unauthorized security context generated for request GET /v2/
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/lib/http/error.go:59]: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized: unauthorized"}]}
nginx           | 172.19.0.3 - "GET /v2/ HTTP/1.0" (8080) 401 76 "-" "docker/19.03.13 go/go1.13.15 git-commit/4484c46d9d kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.13 \x5C(windows\x5C))" 0.001 0.000 .
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id d2631dcc-80de-482c-9d84-858a17d74e8f to the logger for the request GET /service/token
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:52]: In artifact info middleware, url: /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/common/dao/user.go:277]: Check if user admin is super user
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/core/auth/authenticator.go:139]: Current AUTH_MODE is db_auth
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/server/middleware/security/basic_auth.go:48][requestID="d2631dcc-80de-482c-9d84-858a17d74e8f"]: a basic auth security context generated for request GET /service/token
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/core/service/token/token.go:35]: URL for token request: /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/core/service/token/creator.go:203]: scopes: []
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/core/service/token/authutils.go:48]: scopes: []
nginx           | 172.19.0.3 - "GET /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.0" (8080) 200 1105 "-" "docker/19.03.13 go/go1.13.15 git-commit/4484c46d9d kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.13 \x5C(windows\x5C))" 0.023 0.024 .
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 82dcb58f-a7b7-4bf5-b38b-cdff3b20881a to the logger for the request GET /v2/
harbor-core     | 2020-10-13T06:42:59Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:52]: In artifact info middleware, url: /v2/
nginx           | 172.19.0.3 - "GET /v2/ HTTP/1.0" (8080) 404 115 "-" "docker/19.03.13 go/go1.13.15 git-commit/4484c46d9d kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.13 \x5C(windows\x5C))" 0.011 0.008 .
```
